# Generated by Django 3.0.4 on 2020-03-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200316_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='available',
            new_name='isAvailable',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='person',
            new_name='user',
        ),
    ]
